# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Redpanda
email: info@redpanda.pro
description: > # this means to ignore newlines until "baseurl:"
  Дизайн и верстка полиграфической продукции, макетирование сайтов, фирменные стили и логотипы. Фото коллажирование, ретушь, иллюстрации.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://redpanda.pro" # the base hostname & protocol for your site
maxtags: 9
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "portfolio"
    values:
      layout: "tag"
